name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.19', '1.20.x' ]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
        cache-dependency-path: '**/go.sum'

    - name: Display Go version
      run: go version
      
    - name: Install dependencies
      run: |
        cd ./resource-cel-validator
        go get ./...
        cd ../tests
        go get -t ./...

    - name: Build & Test
      run: | 
        cd ./resource-cel-validator
        go build -v ./...
        go test -v ./...

    - name: e2e Tests
      run: | 
        cd ./tests
        go test -v ./...
